version: '3.7'

services:
  watchtower:
    container_name: watchtower
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.dev-self-contained
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
#    command: notify-upgrade --interval 10 --http-api-metrics --http-api-token demotoken --debug prometheus grafana parent child --notifications slack --notification-slack-hook-url "https://discord.com/api/webhooks/1351640524947325090/HpEK0NKEjoBCLgrwI5uvRy5pn8Vqdo4mqP0Suq-F2R4jf_wQXr7-1574K74igH9Jlvwv/slack" --notification-slack-thread-id "1351640673526354040"
    command: --interval 10 --http-api-metrics --http-api-token demotoken --debug prometheus grafana parent child --notifications slack --notification-slack-hook-url "https://discord.com/api/webhooks/1351640524947325090/HpEK0NKEjoBCLgrwI5uvRy5pn8Vqdo4mqP0Suq-F2R4jf_wQXr7-1574K74igH9Jlvwv/slack" --notification-slack-thread-id "1351640673526354040"
    environment:
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      WATCHTOWER_NOTIFICATION_URL: "discord://HpEK0NKEjoBCLgrwI5uvRy5pn8Vqdo4mqP0Suq-F2R4jf_wQXr7-1574K74igH9Jlvwv@1351640524947325090?thread_id=1351640673526354040"
#      WATCHTOWER_NOTIFICATIONS: slack
#      WATCHTOWER_NOTIFICATION_URL: "discord://HpEK0NKEjoBCLgrwI5uvRy5pn8Vqdo4mqP0Suq-F2R4jf_wQXr7-1574K74igH9Jlvwv@1351640524947325090"
#      WATCHTOWER_NOTIFICATION_SLACK_THREAD: "1351640673526354040"
      WATCHTOWER_NOTIFICATION_TEMPLATE: " {{- if .Report -}}
                                            {{- with .Report -}}
                                          {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
                                                {{- range .Updated}}
                                          - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
                                                {{- end -}}
                                                {{- range .Fresh}}
                                          - {{.Name}} ({{.ImageName}}): {{.State}}
                                              {{- end -}}
                                              {{- range .Skipped}}
                                          - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
                                              {{- end -}}
                                              {{- range .Failed}}
                                          - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
                                              {{- end -}}
                                            {{- end -}}
                                          {{- else -}}
                                            {{range .Entries -}}{{.Message}}{{\"\n\"}}{{- end -}}
                                          {{- end -}}"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus/
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
  parent:
    image: nginx
    container_name: parent
  child:
    image: nginx:alpine
    labels:
      com.centurylinklabs.watchtower.depends-on: parent
    container_name: child

volumes:
  prometheus: {}
  grafana: {}
